/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class userupdate extends javax.swing.JFrame {

    /**
     * Creates new form userupdate
     */
    public userupdate() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ph = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        anumb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nope = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cind = new javax.swing.JTextField();
        roomm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Ph.no");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(144, 29, 31, 16);
        getContentPane().add(ph);
        ph.setBounds(223, 26, 295, 22);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(443, 54, 72, 23);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 100, 32, 16);
        getContentPane().add(n);
        n.setBounds(220, 90, 300, 22);

        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 150, 50, 16);

        add.setColumns(20);
        add.setRows(5);
        jScrollPane1.setViewportView(add);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 140, 300, 86);

        jLabel5.setText("Aadhar no");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 240, 55, 16);
        getContentPane().add(anumb);
        anumb.setBounds(220, 240, 300, 22);

        jLabel6.setText("Checkin date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 280, 69, 16);

        jLabel7.setText("No.of people");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 320, 69, 16);

        nope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopeActionPerformed(evt);
            }
        });
        getContentPane().add(nope);
        nope.setBounds(220, 320, 300, 22);

        jLabel8.setText("Room Type");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 360, 60, 16);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 360, 72, 23);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 390, 72, 23);
        getContentPane().add(cind);
        cind.setBounds(220, 280, 300, 22);
        getContentPane().add(roomm);
        roomm.setBounds(220, 360, 210, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\colorful-background-with-3d-triangles_23-2148402765.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 690, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 Userhome u = new Userhome();
    u.setVisible(true);
    this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String p = ph.getText();     
PreparedStatement ps;
ResultSet rs;

try{
String q = "SELECT * FROM `room` WHERE `phn`=?";

ps = Myconn.getconnection().prepareStatement(q);
ps.setString(1,p);

rs=ps.executeQuery();

if(rs.next())
{
    n.setText(rs.getString(2));
    add.setText(rs.getString(4));
    anumb.setText(rs.getString(3));
    cind.setText(String.valueOf(rs.getString(6)));
    nope.setText(rs.getString(7));
    roomm.setText(rs.getString(8));
    
}

else{
    JOptionPane.showMessageDialog(null,"number does not exist");
}
}
catch(Exception ex)
{
    System.out.println(ex);
}         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String name = n.getText();
String pho = ph.getText();
String address = add.getText();
String aadhar = anumb.getText();
String checkin = cind.getText();
String people = nope.getText();
String room = roomm.getText();


PreparedStatement ps;
String query="UPDATE `room` SET `uname`=?,`address`=?,`anum`=?,`cin`=?,`nop`=?,`rtype`=? WHERE `phn`=?";

try {
    ps=Myconn.getconnection().prepareStatement(query);
    ps.setString(1,name);
    ps.setString(2,address);
    ps.setString(3,aadhar);
    ps.setString(4,checkin);
    ps.setString(5,people);
    ps.setString(6,room);
    ps.setString(7,pho);
    if(ps.executeUpdate()>0)
    {
        JOptionPane.showMessageDialog(null, "Updated");
    }
    else
    {
        JOptionPane.showMessageDialog(null,"contact number does not exist");
    }
    
}
catch (SQLException ex)
{
  System.out.println(ex);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add;
    private javax.swing.JTextField anumb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cind;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n;
    private javax.swing.JTextField nope;
    private javax.swing.JTextField ph;
    private javax.swing.JTextField roomm;
    // End of variables declaration//GEN-END:variables
}
