/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Userhome extends javax.swing.JFrame {

    /**
     * Creates new form Userhome
     */
    public Userhome() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 60, 130, 20);

        jLabel4.setText("Ph.no :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 100, 130, 20);

        jLabel5.setText("Aadhar number :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 240, 150, 20);

        jLabel6.setText("Check in Date :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 280, 150, 20);

        jLabel7.setText("No.of people :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 310, 140, 20);

        jLabel8.setText("Room type :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 350, 140, 20);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 361, 0, 0);

        jLabel10.setText("Address :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 140, 130, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 140, 234, 80);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 60, 230, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 100, 230, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 240, 230, 22);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(240, 280, 230, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 310, 230, 22);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Single cot");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(240, 350, 98, 21);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Doube cot");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(340, 350, 98, 21);

        jButton1.setText("Booked");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 380, 72, 23);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 100, 0, 0);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 380, 75, 23);

        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Already Booked?");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 410, 90, 16);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("BOOKINGS");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 20, 130, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\colorful-background-with-3d-triangles_23-2148402765.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-10, -10, 660, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    User u = new User();
    u.setVisible(true);
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String n = jTextField1.getText();
        System.out.println(n);    // TODO add your handling code here:
    String p = jTextField2.getText();
        System.out.println(p);
    String a = jTextArea1.getText();
        System.out.println(a);
    String an = jTextField3.getText();
        System.out.println(an);
    SimpleDateFormat da=new SimpleDateFormat("YYYY-MM-dd");
    String cin=da.format(jDateChooser1.getDate());
    System.out.println(cin);
    String nop = jTextField4.getText();
        System.out.println(nop);
    String room = null;
    if(jRadioButton1.isSelected())
    {
        room="Single cot";
    }
     else
    {
        room="Double cot";
    }
    
    
        PreparedStatement ps;
    String query = "INSERT INTO `room`(`uname`,`phn`,`address`,`anum`,`cin`,`nop`,`rtype`)values(?,?,?,?,?,?,?)";
    try 
    {
        ps=Myconn.getconnection().prepareStatement(query);
        
        ps.setString(1,n);
        ps.setString(2,p);
        ps.setString(3,a);
        ps.setString(4,an);
        ps.setString(5,cin);
        ps.setString(6,nop);
        ps.setString(7,room);
    if(ps.executeUpdate()>0)
    {
        JOptionPane.showMessageDialog(null,"Room Booked");
    }
}
catch(Exception ex)
{
    System.out.println(ex);
}   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
userupdate u = new userupdate();
u.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
